# docker-compose.yml
services:
  # AdGuard Home: The primary DNS filter
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host # Required for proper network visibility on Pi
    volumes:
      - ./adguard/conf:/opt/adguardhome/conf
      - ./adguard/work:/opt/adguardhome/work

  # Unbound: The recursive DNS resolver for privacy
  unbound:
    image: klutchell/unbound:latest
    container_name: unbound
    platform: linux/arm64/v8 # Force ARM64 architecture
    restart: unless-stopped
    network_mode: host # Required for proper network visibility on Pi
    volumes:
      - ./unbound/unbound.conf:/etc/unbound/unbound.conf:ro
      - ./unbound/root.hints:/etc/unbound/root.hints:ro
      - ./unbound/root.key:/etc/unbound/root.key:rw
  # # Tailscale: Secure remote access & Exit Node
  # tailscale:
  #   image: tailscale/tailscale:latest
  #   container_name: tailscale
  #   restart: unless-stopped
  #   network_mode: host
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   volumes:
  #     - ./tailscale/state:/var/lib/tailscale
  #     - /dev/net/tun:/dev/net/tun
  #   environment:
  #     - TS_STATE_DIR=/var/lib/tailscale
  #     - TS_USERSPACE=false
