server:
    # Docker Integration
    use-syslog: no
    do-daemonize: no
    chroot: ""

    # Operational
    verbosity: 1
    log-queries: no

    # Network
    interface: 127.0.0.1
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes
    do-ip6: no

    # Recursion
    root-hints: "/etc/unbound/root.hints"

    # Security & Hardening
    harden-glue: yes
    harden-dnssec-stripped: yes
    harden-algo-downgrade: yes
    harden-short-bufsize: yes
    harden-large-queries: yes
    qname-minimisation: yes
    use-caps-for-id: yes
    hide-identity: yes
    hide-version: yes

    # Anti-DNS Rebinding
    private-address: 192.168.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8

    # Performance
    prefetch: yes
    num-threads: 1
    msg-cache-slabs: 1
    rrset-cache-slabs: 1
    infra-cache-slabs: 1
    key-cache-slabs: 1
    rrset-cache-size: 100m
    msg-cache-size: 50m
    so-rcvbuf: 0
    so-sndbuf: 0

    # Access Control
    access-control: 127.0.0.0/8 allow
    access-control: 172.16.0.0/12 allow

# --- Debugging Toggles ---
# verbosity: 3
# log-queries: yes
# interface: 0.0.0.0
